services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-card
    restart: unless-stopped
    ports:
      - "8096:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - /etc/letsencrypt:/etc/letsencrypt:ro
