name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean up old Docker artifacts
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} "
            docker system prune -f
          "

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} "
            cd /home/deployer/apps && 
            rm -rf business-card-client &&
            git clone https://${{ secrets.PERSONAL_TOKEN_GITHUB }}@github.com/SSE-programmer/business-card-client.git || (cd business-card-client && git pull) && 
            cd business-card-client && 
            docker-compose down && 
            docker-compose up -d --build
          "
