name: Nx CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Проверяем наличие lock-файла
      - name: Check for lock file
        id: check-lock
        run: |
          if [ -f "package-lock.json" ]; then
            echo "lock-file=package-lock.json" >> $GITHUB_OUTPUT
          else
            echo "No lock file found!" >&2
            exit 1
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Nx globally
        run: npm install -g nx

      - name: Install dependencies
        run: npm ci

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: |
            .nx/cache
            node_modules
          key: ${{ runner.os }}-nx-${{ hashFiles('yarn.lock') }}

      - name: Run tests
        run: nx affected:test --base=main --head=HEAD

      - name: Build affected projects
        run: nx affected:build --prod --parallel --base=main --head=HEAD
